# 1rtos-container-image-scan.yml
# Container CVE Scanner ( dispatch Event )
#
# Runs Trivy CVE scan for CRITICAL, HIGH & MEDIUM on main tag

name: container-image-scan
on:
  workflow_dispatch:

jobs:
  cveScanImage:
    runs-on: fmos-ubuntu-latest
    steps:
      - name: CVE scan main.stg image before promoting
        uses: intel-innersource/os.rtos.zephyr.devops.ci/actions/trivy-cve-scan@main
        with:
          container-url: 'amr-registry.caas.intel.com/zephyrproject/sdk-docker-intel:main.stg'
          cve-level: 'CRITICAL,HIGH,MEDIUM'
          dockerio-user: ${{ secrets.DOCKERIO_USER }}
          dockerio-pass: ${{ secrets.DOCKERIO_PASSWD }}
