# 1rtos-container-image-scan.yml
# Container CVS Scanner ( dispatch Event )
#
# Runs Trivy CVS scan for CRITICAL, HIGH & MEDIUM on main tag

name: container-image-scan
on:
  workflow_dispatch:

jobs:
  scanImage:
    runs-on: testhead
    steps:
      - uses: actions/checkout@v2
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '127.0.0.1:5000/sdk-docker-intel:main'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH,MEDIUM'
