# 1rtos-container-image-backport.yml
# Back-ports changes to /1rtos to legacy container images

name: container-image-backport
concurrency: 1rtos_container_cd
on:
  workflow_dispatch:
  push:
    branches:
      - main-intel
    paths:
      - '1rtos/**'

jobs:
  backport-1rtos:
    runs-on: fmos-ubuntu-latest
    strategy:
      matrix:
        img: [ 'amr-registry.caas.intel.com/zephyrproject/sdk-docker-intel' ]
        tag: [v2.7-branch, v2.6-branch, v2.5-branch]
    steps:
      - uses: actions/checkout@v2
      - name: 'Rebuild container latest apt update + fresh copy of /opt/1rtos contents, then and push to registry.'
        run: |
            docker login -u ${{ secrets.CAAS_PRODUCTION_BOT_USERNAME }} -p ${{ secrets.CAAS_PRODUCTION_BOT_PASSWD }} amr-registry.caas.intel.com && \
            docker pull ${{ matrix.img }}:${{ matrix.tag }} && \
            docker tag ${{ matrix.img }}:${{ matrix.tag }} ${{ matrix.img }}:${{ matrix.tag }}.last && \
            docker push ${{ matrix.img }}:${{ matrix.tag }}.last && \
            echo -e 'FROM ${{ matrix.img }}:${{ matrix.tag }}\nARG HTTPPROXY=\nARG HTTPSPROXY=\nENV http_proxy=$HTTPPROXY\nENV https_proxy=$HTTPSPROXY\nUSER root\nRUN apt-get -y update && apt-get -y upgrade\nCOPY ./1rtos/* /opt/1rtos/\nUSER 1rtosdev' > Dockerfile && \
            docker build --pull --build-arg UID=$(id -u) --build-arg GID=$(id -g) --build-arg HTTPPROXY=$http_proxy --build-arg HTTPSPROXY=$https_proxy -t ${{ matrix.img }}:${{ matrix.tag }} . && \
            docker push ${{ matrix.img }}:${{ matrix.tag }} && \
            docker logout amr-registry.caas.intel.com && \
            docker rmi ${{ matrix.img }}:${{ matrix.tag }}.last && docker rmi ${{ matrix.img }}:${{ matrix.tag }}
        shell: bash
