# 1rtos-container-image-push.yml
# Container CD Workflow - Push Event
# 
# Runs Trivy CVE scan & if passing main.stg is tagged -> main & pushed to registry.
#
# Expects main.stg image already built in registry
#
name: container-image-push
concurrency: 1rtos_container_cd
on:
  push:
    branches:
      - main-intel

jobs:
# .stg container image is already built, scan once more and then retag+push
#   This step can run on our 'uzdo-ubuntu-latest' VMs - task only involves container registry push/pull
  scanAndPromoteImage:
    runs-on: fmos-ubuntu-latest
    steps:
      - name: CVE scan main.stg image before promoting
        uses: intel-innersource/os.rtos.zephyr.devops.ci/actions/trivy-cve-scan@main
        with:
          container-url: 'amr-registry.caas.intel.com/zephyrproject/sdk-docker-intel:main.stg'
          cve-level: 'CRITICAL'
          dockerio-user: ${{ secrets.DOCKERIO_USER }}
          dockerio-pass: ${{ secrets.DOCKERIO_PASSWD }}
      - name: retag and push image to production registry
        run: |
            docker login -u ${{ secrets.CAAS_PRODUCTION_BOT_USERNAME }}  -p ${{ secrets.CAAS_PRODUCTION_BOT_PASSWD }} amr-registry.caas.intel.com && \
            docker pull amr-registry.caas.intel.com/zephyrproject/sdk-docker-intel:main.stg && \
            docker tag amr-registry.caas.intel.com/zephyrproject/sdk-docker-intel:main.stg amr-registry.caas.intel.com/zephyrproject/sdk-docker-intel:main && \
            docker push amr-registry.caas.intel.com/zephyrproject/sdk-docker-intel:main && \
            docker rmi amr-registry.caas.intel.com/zephyrproject/sdk-docker-intel:main.stg && \
            docker logout amr-registry.caas.intel.com
        shell: bash
