name: 1RTOS-sdk-docker-intel-CD
on:
  pull_request:
    branches:
      - main-intel
  workflow_dispatch:

jobs:
  dockerBuildPush: 
    runs-on: testhead
    steps:
      - uses: actions/checkout@v2
      - run: |
          set       
          chmod 777 entrypoint.sh
          docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) --build-arg HTTPPROXY=$http_proxy --build-arg HTTPSPROXY=$https_proxy --build-arg NOPROXY=$no_proxy -t 127.0.0.1:5000/sdk-docker-intel:main .
          docker push 127.0.0.1:5000/sdk-docker-intel:main
        shell: bash
