name: container-image-build
concurrency:
  group: ${{ github.workflow }}-${{ github.event_name }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  push:
    branches:
    - main
    tags:
    - v*
  pull_request:
    branches:
      - main
  workflow_dispatch:

env:
  registry: 'amr-registry.caas.intel.com'
  project: 'zephyrproject'

jobs:
  build:
    runs-on: fmos-guest-ubuntu-12c
    defaults:
      run:
        shell: bash
    steps:
      - name: Docker Tag
        id: docker_tag
        run: |
          echo ${{ github.event_name }}
          # If push due to a normal commit to main GITHUB_REF will look like
          # refs/heads/master convert that to 'latest'
          if [ ${GITHUB_REF} == "refs/heads/main" ]; then
            echo ::set-output name=DOCKER_TAG::latest;
          elif [ ${{ github.event_name }} == 'pull_request' ]; then
            echo ::set-output name=DOCKER_TAG::${{github.event.pull_request.number}};
          else
            # If push due to a tag GITHUB_REF will look like refs/tags/TAG-FOO
            # chop of 'refs/tags' so DOCKER_TAG=TAG-FOO
            echo ::set-output name=DOCKER_TAG::${GITHUB_REF/refs\/tags\//};
          fi
      - uses: actions/checkout@v2
      - name: build lite container image
        env:
          DOCKER_TAG: ${{ steps.docker_tag.outputs.DOCKER_TAG }}
        run: |
          chmod 777 entrypoint.sh
          docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) \
            --build-arg HTTPPROXY=$http_proxy \
            --build-arg HTTPSPROXY=$https_proxy \
            --build-arg NOPROXY=$no_proxy \
            --build-arg ARTIFACTORY_API_KEY=${{ secrets.SYS_TMBUILD_ARTIFACTORY_API_KEY }} \
            --target ci-lite \
            -t ${{ env.registry }}/${{ env.project }}/ci-lite:${DOCKER_TAG} .
      - name: build XCC container image
        env:
          DOCKER_TAG: ${{ steps.docker_tag.outputs.DOCKER_TAG }}
        run: |
          docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) \
            --build-arg HTTPPROXY=$http_proxy \
            --build-arg HTTPSPROXY=$https_proxy \
            --build-arg NOPROXY=$no_proxy \
            --build-arg ARTIFACTORY_API_KEY=${{ secrets.SYS_TMBUILD_ARTIFACTORY_API_KEY }} \
            --target ci-xcc \
            -t ${{ env.registry }}/${{ env.project }}/ci-xcc:${DOCKER_TAG} .
      - name: build main container image
        env:
          DOCKER_TAG: ${{ steps.docker_tag.outputs.DOCKER_TAG }}
        run: |
          docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) \
            --build-arg HTTPPROXY=$http_proxy \
            --build-arg HTTPSPROXY=$https_proxy \
            --build-arg NOPROXY=$no_proxy \
            --build-arg ARTIFACTORY_API_KEY=${{ secrets.SYS_TMBUILD_ARTIFACTORY_API_KEY }} \
            --target ci-sdk \
            -t ${{ env.registry }}/${{ env.project }}/ci-sdk:${DOCKER_TAG} .
      - name: build Coverity container image
        env:
          DOCKER_TAG: ${{ steps.docker_tag.outputs.DOCKER_TAG }}
        run: |
          docker build --build-arg UID=$(id -u) --build-arg GID=$(id -g) \
            --build-arg HTTPPROXY=$http_proxy \
            --build-arg HTTPSPROXY=$https_proxy \
            --build-arg NOPROXY=$no_proxy \
            --build-arg ARTIFACTORY_API_KEY=${{ secrets.SYS_TMBUILD_ARTIFACTORY_API_KEY }} \
            --target ci-coverity \
            -t ${{ env.registry }}/${{ env.project }}/ci-coverity:${DOCKER_TAG} .
      - name: login into caas
        if: ${{ github.event_name == 'push' }}
        run: |
          echo '${{ secrets.CAAS_PRODUCTION_BOT_PASSWD }}' | \
          docker login -u '${{ secrets.CAAS_PRODUCTION_BOT_USERNAME }}'  \
            --password-stdin ${{ env.registry }}

      - name: push lite image
        env:
          DOCKER_TAG: ${{ steps.docker_tag.outputs.DOCKER_TAG }}
        if: ${{ github.event_name == 'push' }}
        run: |
          docker push ${{ env.registry }}/${{ env.project }}/ci-lite:${DOCKER_TAG}

      - name: push XCC image
        env:
          DOCKER_TAG: ${{ steps.docker_tag.outputs.DOCKER_TAG }}
        if: ${{ github.event_name == 'push' }}
        run: |
          docker push ${{ env.registry }}/${{ env.project }}/ci-xcc:${DOCKER_TAG}

      - name: push Coverity image
        env:
          DOCKER_TAG: ${{ steps.docker_tag.outputs.DOCKER_TAG }}
        if: ${{ github.event_name == 'push' }}
        run: |
          docker push ${{ env.registry }}/${{ env.project }}/ci-coverity:${DOCKER_TAG}

      - name: push main image
        env:
          DOCKER_TAG: ${{ steps.docker_tag.outputs.DOCKER_TAG }}
        if: ${{ github.event_name == 'push' }}
        run: |
          docker push ${{ env.registry }}/${{ env.project }}/ci-sdk:${DOCKER_TAG}

      - name: registry logout
        if: ${{ always() }}
        run: |
          docker logout ${{ env.registry }}
          docker logout
          true

