# Copyright (c) 2020 Linaro Limited.
# SPDX-License-Identifier: Apache-2.0

# Git Hub workflow to publish a container to docker hub
# This only happens on commits or tags.

name: Docker Publish

on: [push]

env:
  DOCKER_USER: zephyrprojectrtos
  DOCKER_REPO: ci
  DOCKER_REPO2: zephyr-build

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'zephyrproject-rtos/docker-image'
    steps:
    - name: Docker Tag
      id: docker_tag
      run: |
        # If push due to a normal commit to master GITHUB_REF will look like
        # refs/heads/master convert that to 'latest'
        if [ ${GITHUB_REF} == "refs/heads/master" ]; then
           echo ::set-output name=DOCKER_TAG::latest;
        else
           # If push due to a tag GITHUB_REF will look like refs/tags/TAG-FOO
           # chop of 'refs/tags' so DOCKER_TAG=TAG-FOO
           echo ::set-output name=DOCKER_TAG::${GITHUB_REF/refs\/tags\//};
        fi

    - uses: azure/docker-login@v1
      with:
        username: ${{ env.DOCKER_USER }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - uses: actions/checkout@v2

    - name: build
      env:
        DOCKER_TAG: ${{ steps.docker_tag.outputs.DOCKER_TAG }}
      run: |
        df -h
        # remove a few things to free up space
        sudo rm -rf "/usr/local/share/boost"
        sudo rm -rf "/usr/local/lib/android"
        sudo rm -rf "$AGENT_TOOLSDIRECTORY"
        df -h
        docker build . --file Dockerfile --tag docker.io/${DOCKER_USER}/${DOCKER_REPO}:${DOCKER_TAG}
        docker build . --file Dockerfile.user --build-arg FROM_TAG=${DOCKER_TAG} --tag docker.io/${DOCKER_USER}/${DOCKER_REPO2}:${DOCKER_TAG}

    - name: push
      env:
        DOCKER_TAG: ${{ steps.docker_tag.outputs.DOCKER_TAG }}
      run: |
        docker push docker.io/${DOCKER_USER}/${DOCKER_REPO}:${DOCKER_TAG}
        docker push docker.io/${DOCKER_USER}/${DOCKER_REPO2}:${DOCKER_TAG}
